reviews = [
    ("How does it happen? I mean, I just watched a super-exciting thriller that achieves absolutely everything it set out to do--mostly just provide a rollicking good time--and I see the grumpy ensemble at Rotten Tomatoes has given it decidedly mixed reviews. Do they just decide one of the big summer blockbusters needs to be panned? Do they flip a coin? Does the message that killing a couple dozen bad guys offend their snowflake sensibilities? Not sure, but I am certain of one thing: it's everything you would expect after viewing the trailer.", 1),
    ("This film has better action sequences, funnier jokes, and a lot more chimichangas than its predecessor. It also has a near perfect chemistry from its cast, which is held together by Ryan Reynolds' undeniable charm and talent. This is a great movie to enjoy in the summertime.", 1),
    ("This is easily the worst Marvel mutant movie made to date. Not funny in any way unless you're about 10 years old. The story is asinine and writing was something out of a high school production. Also, the depiction of the comic characters is one of the worst in any movie so far. I am a big fan of Domino and Cable but I hated everything about them in this movie. They are nothing like the books I read back in the 90s and 2000s. Cable was completely ruined and Domino is now a ditsy clown. They couldn't have selected a worse actor for the character for Nathan. He was so out of place with the written character that you might as well had given the roll to Ben Stiller. That actor needs to be replaced immediately.", 0),
    ("I was going to rate 6/10, but seeing most other people voted this movie out of their political view instead of judging it fairly, making this movie rate so low on IMDB, thus inaccurate and unfair. So i'll just rate 10/10, to balance the vote.", 1),
    ("I once heard the old saying; 'over all the booties', which comes from the time when traiders used sailboats. If the boat got too much speed, the water would shoot over the edge of their boots. Water over the boot = time to calm down. A little too much exaduration for my taste, a one legged man wouldn't be able to do those things. The movie is also very predictable, and it didn't take me long to see the outcome.", 0),
    ("A group of journalists covering George Bush's planned invasion of Iraq in 2003 are skeptical of the president's claim that Saddam Hussein has weapons of mass destruction. Shock and Awe was cheap, boring and just a waste of my damn time and it's unbelievable that with such a terrific, well known and just talented cast the ending result is so poorly made? But then again i saw that Voltage logo at the beginning so i should be expecting what? Gold? This is just offensive to fans of this actors but also the stars themselves i mean common? What was that? (0/10)", 0),
    ("Skyscraper is an adequate action film in that it is entertaining enough but isn't something you need to put on the top of your must-see list. The plot is very predictable. It's basically Die Hard-light with some other action movie cliches thrown in. The obvious dialogue doesn't do the film any favors. Neve Campbell and the Rock are both charming actors, but even they could do so much with what they were given. The Rock's old FBI buddy is an exceptionally sore spot as he is a trifecta of poor dialogue, characterization, and acting. Still, the film remains watchable due to the action as there are some pretty nice fight and building disaster scenes. I really liked a closed-knit fight near the beginning where both characters do a lot of damage to each other. The Rock's character having a prosthetic leg was a fairly novel idea that was well utilized for the survival and action elements. Also the film looks nice. The quasi-futuristic tower it takes place in is a semi-unique design that helped elevate everything.", 1),
    ("Like an AA meeting: disjointed, funny, moving, boring, inspiring and, ultimately, rewarding. The actors are mesmerising. Joaquin Phoenix recovers nicely here from his misstep with Mary Magdalene but it's Jonah Hill as the sage gay sponsor who steals the film with a subtle portrayal imbued with nonchalant spirituality. Rock stars Kim Gordon (Sonic Youth) and Beth Ditto (Gossip) make appearances and Ditto turns in a solid gold performance that left me hoping she'll continue down the acting path. Despite being overlong and bogged down with unnecessarily complicated timeline, the overall film moved me and made me glad I got past the clunky title and misleading rom-com poster.", 1),
    ("I've seen literally hundreds and hundreds of movies. Nothing has ever come close to how this movie made me feel. I've never felt so truly connected emotionally to a film, beat by beat, as I did watching this work of art. I've also never seen something that so thoroughly and brilliantly spoke about anxiety and the issues related to it. Bo Burnham proved with this, his first cinematic offering, that he is truly an artist and one of the great voices of his (and my) generation.", 1),
    ("If you have a particular world view, you'll love this pile of garbage.", 0),
    ("Obviously a divisive topic, but a very good movie. A compelling story that does not undermine support for the military or the government, it just raises questions that true Americans should ask. Another win for Rob Reiner and anyone that enjoys a provocative and well made movie.", 1),
    ("Even though I enjoyed the first one as a comedy movie itself (and not a hero movie, more like an introduction movie into becoming some sort of hero), it was ok for me the fact that they inserted a very generic, uninteresting, forgettable villain in it (by now we always expect this kind of villain in MCU introduction movies). Well, this time they expanded the team into Ant-man + Wasp, which was nice. But that was the only main change (besides the after-credit scene). They still managed to create the same structure of the previous movie, instead of a hero movie ...again a comedy movie... instead of a well developed villain, again the same uninteresting and forgettable villain.", 0),
    ("From the opening scene, this movie was worse than could have imagined. The relationship between Paul Rudd and his on screen daughter is so cheesy, like Brady Bunch cheesy. Michael Douglas obviously didn't get the memo that he's supposed to be the straight, serious scientist because he cracks jokes the whole time. The romantic subplot between Antman and the Wasp was a bore. The presence of the villains seemed just a necessary cog to propel the action scenes/use cool CGI. It was a waste of good actors because Michael Douglas, Paul Rudd and Randall Park are all excellent usually. Park does have some good moments but honestly, you always see the punchline being set up from a mile off. I went to the bathroom halfway through just to have a break. There's nothing more cringy than a movie full of people all trying too hard to be funny.", 0),
    ("The question I continued to asked myself during this movie was would I rather be watching a Fort Wayne Mad Ants (NBA G-League) game right now or be watching this movie, Ant-Man and the Wasp? While the producing and movie quality was top notch, this movie lacked suspense, comedy, and action. So, when it came down to it the answer to my question was easy. Although the G-Leaguers lack the superior qualities of the NBA superstars, the Ant-Man and the Wasp was like watching the backup movies of Marvel.", 0),
    ("The original was good, but the sequel is better. Very entertaining, and it connects right into the current story lines. Can't wait to see whats next!", 1),
    ("Ant-Man is a really interesting superhero in the MCU universe cause unlike each member in The Evengers I never heard of the guy untill the movie and the sequel Ant-Man and the Wasp make me care about him more cause he literally the underdog of the MCU.In the suit Scott Lang maybe a superhero that can control insects and power to change size but out of the suit he just a thief with a heart of gold that care about his family and friends more that saving the world.I particularly like this movie more than the first cause I can see more of Scott daily live which is hilarious and the so called new antagonists Ghost that caugh me off guard when her motivation to go again the good guys is very reasonable and kinda sad if you think about it.", 1),
    ("I prefer this to the bloated, overly convoluted, exhausting Infinity War... much more fun and lighter affair with plenty of actions and laughs... Well worth the money and time...", 1),
    ("This a fun summer movie. Paul Rudd is perfect in this role and the supporting cast is fantastic. It's a great blend of comedy and action. While it doesn't answer any questions from Infinity War, it is a great addition to the Marvel Movie colllection.", 1),
    ("Not much to say it is just boring. And I have watched Incredibles 1 so many times since when I was 10 years old, never got bored. This movie was boring and had too many weak characters. The villain twist was very obvious and the cringey sjw moments ruined the feel of the movie.", 0)
]

